# Generated by Django 5.2.6 on 2025-09-19 14:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('seed', models.CharField(max_length=64)),
                ('max_hp', models.IntegerField(default=20)),
                ('hp', models.IntegerField(default=20)),
                ('turn', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('ongoing', 'ongoing'), ('won', 'won'), ('lost', 'lost')], default='ongoing', max_length=10)),
                ('deck', models.JSONField(default=list)),
                ('discard', models.JSONField(default=list)),
                ('weapons', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d20', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('bonus', models.IntegerField(default=0)),
                ('total', models.IntegerField()),
                ('context', models.CharField(default='combat', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='game.run')),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.run')),
            ],
        ),
    ]
