# Generated by Django 5.2.6 on 2025-09-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='weapons',
            new_name='board',
        ),
        migrations.AddField(
            model_name='run',
            name='combo_len',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='descida_ate2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='run',
            name='emptied_this_turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='equip_session',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='final_scored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='run',
            name='power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='score_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='session_points',
            field=models.IntegerField(default=0),
        ),
    ]
