# Generated by Django 5.2.6 on 2025-09-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_weapons_run_board_run_combo_len_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-points', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['player_name'], name='game_score_player__974e26_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['-points'], name='game_score_points_0ff2c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('run', 'player_name'), name='uniq_score_per_run_player'),
        ),
    ]
